on: push
jobs:
  deploy:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '12'
    - run: yarn
    - run: yarn dist
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - run: yarn release
      if: ${{ github.ref == 'refs/heads/main' }}
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
